### ISSUE TITLE
Examples using dress_socks with FTP

### ISSUE THREAD

**Issue by ruehsn** [Chowly/dress_socks#3]
I am trying to create FTPS connection through a SOCKS 5 tunnel on a Windows machine and having trouble, I think because of C dependences of net:ftp gem (aka the SOCKSocket in this line: ```if defined? SOCKSSocket and ENV["SOCKS_SERVER"] ``` )

So I think the dress socks would be good solution but not sure how to incorporate it... could you provide some examples how I you use it?

**Comment by ruehsn** [comment]
Thanks to @gammons I was able to figure I need to monkey patch the ```net/ftp``` gem:

``` ruby
require "net/ftp"
require 'dress_socks'  #https://github.com/Chowly/dress_socks

#monkey patch to use dress socks socket:
class Net::FTP   
  #https://github.com/ruby/net-ftp/blob/master/lib/net/ftp.rb#L366
  def open_socket(host, port) # :nodoc:
    return DressSocks::Socket.new(host, port, 
      socks_server: '127.0.0.1', socks_port: '9090')
  end
end
```

Its able to connect to FTP server successfully but timeout whenever trying to do some useful work:
``` ruby    
def test_dress_socks()
  ftp = Net::FTP.new(@host, connection_params) 
  ftp.dir
  ftp.chdir('..')
  puts "~~~~~~~~~~~ fails hear"
  ftp.close
end

test_dress_socks()
```
output:
```
PS C:\#Ruby\ftp> ruby .\gp_mf_ftp_dress_socks.rb
connect: 10.1.4.20, 2021
get: 220-SUFTPSEC IBM FTP CS V2R4 at hog1, 09:08:18 on 2022-10-24.
get: 220 Connection will close if idle for more than 5 minutes.   
put: AUTH TLS
get: 234 Security environment established - ready for negotiation
put: PBSZ 0
get: 200 Protection buffer size accepted
put: PROT P
get: 200 Data connection protection set to private
put: USER W951H66
get: 331 Send password please.
put: PASS ********
get: 230 W951H66 is logged on.  Working directory is "W951H66.".
put: TYPE I
get: 200 Representation type is Image
put: TYPE A
get: 200 Representation type is Ascii NonPrint
put: PASV
get: 227 Entering Passive Mode (10,1,4,20,30,88)
put: LIST
put: TYPE I
C:/Ruby31/lib/ruby/gems/3.1.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<DressSocks::Socket:fd 3, AF_INET, 127.0.0.1, 59311> (Net::ReadTimeout)
        from C:/Ruby31/lib/ruby/gems/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:1548:in `rbuf_fill'    
```

The port numbers don't match (passive mode using: 7768 [30*256+88] but timeout states: 59311) but I don't know if this is real problem or just function of SOCKS5 proxy that local/remote port numbers don't match up.

**Comment by j-mcnally** [comment]
Heyo, gem author here.

I'll be honest, ive never used it with FTP, i would almost certainly assume this is an issue related to passive mode FTP and socks, passive mode i believe opens / connects to a lot of ports other than 21 to get its job done and probably opens additional sockets? Not really sure though, all im somewhat confident we can do with DressSockets is replace a single TCPSocket with a TCPSocket tunneled through a SOCKS proxy.

**Comment by j-mcnally** [comment]
You could also try to define a stub for SOCKSSocket that uses Desssocks as the polyfill incase there are other SOCKSSocket calls your missing in the ftp code.

**Comment by j-mcnally** [comment]
In connection_params can you test with passive set to  false?

**Comment by ruehsn** [comment]
Thanks for the reply.

I haven't had much luck using Active FTP, even without SOCKS proxy:

``` ruby
def connection_params
  { port:     '2021',
    ssl:      { verify_mode: OpenSSL::SSL::VERIFY_NONE},
    passive:    false,
    debug_mode: true,
    username: $user_name,
    password: $hog_password}
end

@host = '10.1.4.20'
def test_ftps()
  ftp = Net::FTP.new(@host, connection_params) 
  ftp.dir
end
```

Output:
```
connect: 10.1.4.20, 2021
get: 220-SUFTPSEC IBM FTP CS V2R4 at hog1, 19:08:43 on 2022-10-24.
get: 220 Connection will close if idle for more than 5 minutes.
put: AUTH TLS
get: 234 Security environment established - ready for negotiation
put: PBSZ 0
get: 200 Protection buffer size accepted
put: PROT P
get: 200 Data connection protection set to private
put: USER W951H66
get: 331 Send password please.
put: PASS ********
get: 230 W951H66 is logged on.  Working directory is "W951H66.".
put: TYPE I
get: 200 Representation type is Image
put: TYPE A
get: 200 Representation type is Ascii NonPrint
put: PORT 10,42,150,169,199,104
get: 200 Port request OK.
put: LIST
put: TYPE I
C:/Ruby31/lib/ruby/gems/3.1.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<Socket:fd 3> (Net::ReadTimeout)
        from C:/Ruby31/lib/ruby/gems/3.1.0/gems/net-ftp-0.1.3/lib/net/ftp.rb:1548:in `rbuf_fill'
```

I've been told that for Active FTP, I should use port 2021 for command port and 2020 for the data port but I don't know how/where I would set the Data Port value...

**Comment by ruehsn** [comment]
for your polyfill idea are you saying I should:

```ruby
SOCKSSocket = DressSocks::Socket.new(@host, '9090', socks_server: '127.0.0.1', socks_port: '9090')
```

I still get a ReadTimeout with that add code.

**Comment by ruehsn** [comment]
I found a solution:

``` ruby
$socks_server = '127.0.0.1'
$socks_port   = '9090'

#https://github.com/ruby/net-ftp/blob/master/lib/net/ftp.rb#L366
# #monkey patch to use dress socks socket:
class Net::FTP   
  def open_socket(host, port) # :nodoc:
    puts "ignoring passed host: #{host}" unless host.eql?(@host)
    puts "socks5: #{$socks_server}:#{$socks_port}"
    puts "opening socket: #{@host}:#{port}"
    return DressSocks::Socket.new(@host, port, 
      socks_server: $socks_server, socks_port: $socks_port)
  end
end
```

The problem was https://github.com/ruby/net-ftp/blob/332f431b8e15ca26335cb2e75417e7dcbe7d4a5a/lib/net/ftp.rb#L1406 

By default the FTP gem looks up the host IP address of the connecting of the connecting socket which is the SOCKS server not the FTP host.  Using the instance variable ```@host```  instead of the host value passed in ensures its uses the correct IP address.
